# Test cases for 7-base_geometry.py

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

# Valid cases
>>> bg = BaseGeometry()
>>> bg.integer_validator("width", 10)
>>> bg.integer_validator("height", 20)
>>> bg.integer_validator("my_int", 12)
>>> bg.integer_validator("", 12)
>>> bg.integer_validator(123, 456)
>>> bg.area()
Traceback (most recent call last):
  ...
Exception: area() is not implemented


# Error cases
# 1
>>> bg.integer_validator()
Traceback (most recent call last):
  ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'


# 2
>>> bg.integer_validator("temperature", True)
Traceback (most recent call last):
  ...
TypeError: temperature must be an integer


# 3
>>> bg.integer_validator("name")
Traceback (most recent call last):
  ...
TypeError: integer_validator() missing 1 required positional argument: 'value'


# 4
>>> bg.integer_validator("name", "Caesar")
Traceback (most recent call last):
  ...
TypeError: name must be an integer


# 5
>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
  ...
ValueError: age must be greater than 0


# 6
>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
  ...
ValueError: distance must be greater than 0


# 7
>>> bg.integer_validator("number", "123")
Traceback (most recent call last):
  ...
TypeError: number must be an integer


# 8
>>> bg.integer_validator("value", None)
Traceback (most recent call last):
  ...
TypeError: value must be an integer


# 9
>>> bg.integer_validator("infin", float('inf'))
Traceback (most recent call last):
  ...
TypeError: infin must be an integer


# 10
>>> bg.integer_validator("nan", float('nan'))
Traceback (most recent call last):
  ...
TypeError: nan must be an integer


# 11
>>> bg.integer_validator("counter", 3.14)
Traceback (most recent call last):
  ...
TypeError: counter must be an integer


# 12
>>> bg.integer_validator("quantity", [1, 2, 3])
Traceback (most recent call last):
  ...
TypeError: quantity must be an integer


#13
>>> bg.integer_validator("set", {1, 2, 3})
Traceback (most recent call last):
  ...
TypeError: set must be an integer


# 14
>>> bg.integer_validator("tuple", (1, 2, 3))
Traceback (most recent call last):
  ...
TypeError: tuple must be an integer


# 15
>>> bg.integer_validator("flag", {"key": "value"})
Traceback (most recent call last):
  ...
TypeError: flag must be an integer


# 16
>>> bg.integer_validator("amount", 0)
Traceback (most recent call last):
  ...
ValueError: amount must be greater than 0


# 17
>>> bg.integer_validator("size", -7)
Traceback (most recent call last):
  ...
ValueError: size must be greater than 0
